import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// We will create this component next
import ClientLayoutWrapper from "@/components/ClientLayoutWrapper";
// Assuming you have shadcn/ui setup, let's add the Toaster
// import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/*
          This wrapper will handle the session check and
          show the address modal if needed.
        */}
        <ClientLayoutWrapper>
          {children}
        </ClientLayoutWrapper>
        {/* Toaster for showing success/error messages */}
        {/* <Toaster /> */}
      </body>
    </html>
  );
}